# fly.toml app configuration file generated for wallet-hominio-box on 2025-05-14T10:29:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wallet-hominio-box'
primary_region = 'fra'

[build]
dockerfile = "packages/wallet/Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
