# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: Production
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set Fly.io Secrets
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl secrets set \
            PUBLIC_BASE_URL="${{ secrets.PUBLIC_BASE_URL }}" \
            BETTER_AUTH_URL="${{ secrets.PUBLIC_BASE_URL }}" \
            BETTER_AUTH_SECRET="${{ secrets.SECRET_BETTER_AUTH_SECRET }}"
            SECRET_DATABASE_URL_AUTH="${{ secrets.SECRET_DATABASE_URL_AUTH }}" \
            SECRET_GOOGLE_CLIENT_ID="${{ secrets.SECRET_GOOGLE_CLIENT_ID }}" \
            SECRET_GOOGLE_CLIENT_SECRET="${{ secrets.SECRET_GOOGLE_CLIENT_SECRET }}" \
      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
